//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContacBookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public long ID { get; set; }
        public string Keys { get; set; }
        public string Contents { get; set; }
    }
}
